In [1]:
print("hello world")

hello world


In [1]:
#creating numpy , 2 d arrays and working with 
import numpy as np


In [2]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [3]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.size(arr2)

6

In [9]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr7=np.linspace(10,20,30)
arr7

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [15]:
arr8=arr7.copy()
arr8

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [16]:
arr1


array([1, 2, 3, 4, 5, 6])

In [18]:
arr1.shape

(6,)

In [19]:
arr7.shape

(30,)

In [23]:
arr9=np.array(([1,2],[2,4],[5,7],[67,77],
               [1,2],[3,4],
               [1,7],[67,67]))
arr9
arr9.shape

(8, 2)

In [25]:
arr9.ndim

2

In [26]:
arr1.size

6

In [ ]:
#no of items is the size of the array
arr9.size

16

In [ ]:
#it is the size of float
arr9.itemsize

8

In [ ]:
#it tells the the datatype
arr9.dtype

dtype('int64')

In [34]:
#it is used to change the data type of the existing array
#it is used in cleaning the data nad memory management
arr9.astype('float')

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 5.,  7.],
       [67., 77.],
       [ 1.,  2.],
       [ 3.,  4.],
       [ 1.,  7.],
       [67., 67.]])

In [ ]:
lista=range(100)
arr11 = np.arange(100)

In [1]:
import sys

In [5]:
import numpy as np
import sys

lista = range(100)

arr11 = np.arange(100)

print(sys.getsizeof(87) * len(lista))

2800


In [6]:
print(arr11.itemsize*arr11.size)

800


In [12]:
import time
X = range(10000000)
y=range(10000000,20000000)
start_time = time.time()

c = [(X,y)for X,y in zip(X,y)]
print(time.time()-start_time)

0.8466794490814209


In [13]:
a = np.arange(10000000)
b=np.arange(10000000,20000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)

0.29973411560058594


In [2]:
import numpy as np
arr12=np.arange(24).reshape(12,2)
arr12

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [4]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [7]:
arr1[-1]

np.int64(6)

In [12]:
arr12[2:4:,1:3]

array([[5],
       [7]])

In [13]:
#iteration 

In [14]:
arr12


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
for i in arr12:
    print(i)

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]
[10 11]
[12 13]
[14 15]
[16 17]
[18 19]
[20 21]
[22 23]


In [17]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [18]:
import numpy as np

In [19]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [20]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [21]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [22]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [23]:
arr2>3


array([ True,  True,  True,  True,  True,  True])

In [24]:
arr3= np.arange(6).reshape(2,3)
arr4= np.arange(6,12).reshape(3,2)

In [25]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])